export const Players = [
  {
    id: "1",
    name: "Cristiano Ronaldo",
    club: "Manchester United",
    img: "assets/images/images/cr.jpg",
    cost: 20000000,
    info: "Cristiano Ronaldo dos Santos Aveiro was born 5 February 1985 is a Portuguese professional footballer who plays as a forward for Premier League club Manchester United and captains the Portugal national team.",
  },
  {
    id: 2,
    name: "Kante",
    club: "Chelsea",
    img: "assets/images/images/kante.jpg",
    cost: 20000000,
    info: "N Golo Kanté (born 29 March 1991) is a French professional footballer who plays as a central midfielder for Premier League club Chelsea and the France national team. Kanté is widely praised for his work rate and defensive acumen.",
  },
  {
    id: 3,
    name: "Messi",
    club: "PSG",
    img: "assets/images/images/messi.jpg",
    cost: 20000000,
    info: "Lionel Andrés Messi born 24 June 1987, also known as Leo Messi, is an Argentine professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and captains the Argentina national team. Widely regarded as one of the greatest players of all time, Messi has won a record seven Ballon d Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d Or Dream Team. Until leaving the club in 2021.",
  },
  {
    id: 4,
    name: "Neymar",
    club: "PSG",
    img: "assets/images/images/neymar.jpg",
    cost: 20000000,
    info: "Neymar da Silva Santos Júnior (born 5 February 1992), known as Neymar, is a Brazilian professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the Brazil national team. He is considered a versatile player, being able to play as either a central striker, second striker, winger or occasionally as an attacking midfielder. A prolific goalscorer and renowned playmaker, he is regarded as one of the best players in the world. Neymar has scored at least 100 goals for three different clubs, making him one of three players to achieve this",
  },
  {
    id: 5,
    name: "Kane",
    club: "Tottenham",
    img: "assets/images/images/kane.jpg",
    cost: 20000000,
    info: "Harry Edward Kane MBE (born 28 July 1993) is an English professional footballer who plays as a striker for Premier League club Tottenham Hotspur and captains the England national team. Regarded as one of the best strikers in the world, Kane is known for his prolific goalscoring record and ability to link play.[4][5] He ranks as Tottenham second-highest all-time top goalscorer and the third-highest Premier League all-time top goalscorer",
  },
  {
    id: 6,
    name: "Haaland",
    club: "Manchester City",
    img: "assets/images/images/haaland.jpg",
    cost: 20000000,
    info: "Erling Braut Haaland (né Håland; born 21 July 2000) is a Norwegian professional footballer who plays as a striker for Premier League club Manchester City and the Norway national team. Considered one of the best players in the world, he is known for his athleticism, speed and finishing.",
  },
];
export const data = [
  {
    id: 1,
    name: "Cristiano Ronaldo",
    cost: 20000000,
    club: "Manchester United",
    img: "assets/images/cr.jpg",
    info: "Cristiano Ronaldo dos Santos Aveiro GOIH ComM born 5 February 1985 is a Portuguese professional footballer who plays as a forward for Premier League club Manchester United and captains the Portugal national team.",
  },
  {
    id: 2,
    name: "N Golo Kanté",
    cost: 40000000,
    club: "Chelsea",
    img: "assets/images/kante.jpg",
    info: "N Golo Kanté (born 29 March 1991) is a French professional footballer who plays as a central midfielder for Premier League club Chelsea and the France national team. Kanté is widely praised for his work rate and defensive acumen.",
  },
  {
    id: 3,
    name: "Messi",
    cost: 50000000,
    club: "PSG",
    img: "assets/images/messi.jpg",
    info: "Lionel Andrés Messi born 24 June 1987, also known as Leo Messi, is an Argentine professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and captains the Argentina national team. Widely regarded as one of the greatest players of all time, Messi has won a record seven Ballon d Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d Or Dream Team. Until leaving the club in 2021.",
  },
  {
    id: 4,
    name: "Neymar",
    cost: 220000000,
    club: "PSG",
    img: "assets/images/neymar.jpg",
    info: "Neymar da Silva Santos Júnior (born 5 February 1992), known as Neymar, is a Brazilian professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the Brazil national team. He is considered a versatile player, being able to play as either a central striker, second striker, winger or occasionally as an attacking midfielder. A prolific goalscorer and renowned playmaker, he is regarded as one of the best players in the world. Neymar has scored at least 100 goals for three different clubs, making him one of three players to achieve this",
  },
  {
    id: 5,
    name: "Harry Kane",
    cost: 90000000,
    club: "Tottenham",
    img: "assets/images/kane.jpg",
    info: "Harry Edward Kane MBE (born 28 July 1993) is an English professional footballer who plays as a striker for Premier League club Tottenham Hotspur and captains the England national team. Regarded as one of the best strikers in the world, Kane is known for his prolific goalscoring record and ability to link play.[4][5] He ranks as Tottenham second-highest all-time top goalscorer and the third-highest Premier League all-time top goalscorer",
  },
  {
    id: 6,
    name: "Erling Haaland",
    cost: 150000000,
    club: "Manchester City",
    img: "assets/images/haaland.jpg",
    info: "Erling Braut Haaland (né Håland; born 21 July 2000) is a Norwegian professional footballer who plays as a striker for Premier League club Manchester City and the Norway national team. Considered one of the best players in the world, he is known for his athleticism, speed and finishing.",
  },
  {
    id: 7,
    name: "Casemiro",
    cost: 40000000,
    img: "assets/images/casemiro.jpg",
    info: "Carlos Henrique Casimiro (born 23 February 1992), known as Casemiro,[4] is a Brazilian professional footballer who plays as a defensive midfielder for Premier League club Manchester United and the Brazil national team. He is widely regarded as one of the best defensive midfielders in the world. Formed at São Paulo, where he scored 11 goals in 111 official games, Casemiro moved to Real Madrid in 2013, and also spent 2014–15 on loan at Porto. He was part of the Real Madrid squad that won four Champions League titles in five seasons, from 2014 to 2018. In total he won fifteen major trophies at Real Madrid, including five Champions Leagues, three La Liga titles, one Copa del Rey and three FIFA Club World Cups.",
  },
  {
    id: 8,
    name: "Raheem Sterling",
    cost: 56020000,
    img: "assets/images/sterling.jpg",
    info: "Raheem Shaquille Sterling MBE (born 8 December 1994) is an English professional footballer who plays as a winger and attacking midfielder for Premier League club Chelsea and the England national team. Born in Jamaica to Jamaican parents, Sterling moved to London at the age of five. He began his career at Queens Park Rangers before signing for Liverpool in 2010. He was awarded the Golden Boy award in 2014.",
  },
  {
    id: 9,
    name: "Sadio Mané",
    cost: 32000000,
    img: "assets/images/sadio.jpg",
    info: "Sadio Mané (born 10 April 1992) is a Senegalese professional footballer who plays as a forward for Bundesliga club Bayern Munich and the Senegal national team. Considered one of the best players in the world and amongst the greatest African players of all time, he is known for his pressing, dribbling, and speed.",
  },
];
